### PR TITLE
feature: create overload for ingest service methods for adding a spec…

### PR DESCRIPTION
**Pull request by msoelvsteen**
…ific connection

### CODE REVIEW

**Comment by elglogins** [comment]
Hi, can you please change destination branch to 'develop'.

**Comment by elglogins** [comment]
Also, please merge the latest `develop` into your work, since it includes changes for pipelines definition.

**Review by elglogins — CHANGES_REQUESTED** [review]
Please take a look at the comments left.

**Comment by msoelvsteen** [comment]
@elglogins I've merged 'develop' into the feature branch and changed the destination to 'develop'

**Pull request merged**
